/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c83f5a238ae496cd0b09d3b3da7e05dc)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ORIGIN: "http://localhost:5173";
	ENVIRONMENT: "development";
	APPROVED_MODEL_SHA256: "a708b431b48e98647c5d469699b57809a0048de1d81bfe77e1b809c070b11be0";
	ROOMS: DurableObjectNamespace<import("./worker/index").RoomCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "RoomCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "ENVIRONMENT" | "APPROVED_MODEL_SHA256">> {}
}
