/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 676ef456ca2df10cd909c061687cb16b)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ORIGIN: "http://localhost:5173";
	ENVIRONMENT: "development";
	LOG_LEVEL: "warn";
	APPROVED_MODEL_SHA256: "a708b431b48e98647c5d469699b57809a0048de1d81bfe77e1b809c070b11be0";
	MARKET_RPC_URL: "https://sepolia-rollup.arbitrum.io/rpc";
	MARKET_CONTRACT_ADDRESS: "0x82b3b0d498f268fe4cbd197c06cba9352d5ab80a";
	AUTO_MARKET_ROOMS: "tokyo,sydney,sf,paris,nyc,london";
	MARKET_BETTING_WINDOW_SECONDS: "30";
	MARKET_RESOLUTION_WINDOW_SECONDS: "600";
	MARKET_LOWER_BOUND: "10";
	MARKET_UPPER_BOUND: "30";
	MARKET_EXACT_TARGET: "20";
	MARKET_FEE_BPS: "200";
	MARKET_OPERATOR_PRIVATE_KEY: string;
	ROOMS: DurableObjectNamespace<import("./worker/index").RoomCoordinator>;
	MARKET_SCHEDULER: DurableObjectNamespace<import("./worker/index").MarketScheduler>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "RoomCoordinator" | "MarketScheduler";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "ENVIRONMENT" | "LOG_LEVEL" | "APPROVED_MODEL_SHA256" | "MARKET_RPC_URL" | "MARKET_CONTRACT_ADDRESS" | "AUTO_MARKET_ROOMS" | "MARKET_BETTING_WINDOW_SECONDS" | "MARKET_RESOLUTION_WINDOW_SECONDS" | "MARKET_LOWER_BOUND" | "MARKET_UPPER_BOUND" | "MARKET_EXACT_TARGET" | "MARKET_FEE_BPS" | "MARKET_OPERATOR_PRIVATE_KEY">> {}
}
